name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths-ignore:
      # Do not run the pipeline if only Markdown files changed
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Pack extension
        run: npm pack

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: | 
            mherwig-openlens-node-pod-menu-${{ env.RELEASE_VERSION }}.tgz
