name: Build extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Set release version
        run: echo "RELEASE_VERSION=$(node -p 'require('./package.json').version')" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Pack extension
        run: npm pack

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: | 
            mherwig-openlens-node-pod-menu-${{ env.RELEASE_VERSION }}.tgz

      - name: Latest
        uses: softprops/action-gh-release@v0.1.14
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: Latest
          files: | 
            mherwig-openlens-node-pod-menu-${{ env.RELEASE_VERSION }}.tgz